/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ementor.plus;

import static ementor.plus.TabelaAlunos.TableAluno;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class TableTurma extends javax.swing.JFrame {
    
    private String cpf;

    /**
     * Creates new form TableTurma
     */
    public TableTurma(String cpf) {
        this.cpf = cpf;
        initComponents();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        AlunoTurma aluno = new AlunoTurma();
        ArrayList<AlunoTurma> alunoTurmas = aluno.mostrarAlunoTurma(this.cpf);
        ArrayList<Turma> turmas = new ArrayList();
        Turma turma = new Turma();
        for(int i = 0; i < alunoTurmas.size(); i++){
            Turma atual = turma.mostraTurma(alunoTurmas.get(i).getCodigoTurma());
            turmas.add(atual);
        }
        
        DefaultTableModel Tabela = (DefaultTableModel) TabelaTurma.getModel();
        for(int i = 0; i<alunoTurmas.size(); i++){
            Tabela.addRow(new Object[] {alunoTurmas.get(i).getAlunoCPF(), 
                                        turmas.get(i).getNome(), 
                                        alunoTurmas.get(i).getCodigoTurma(),
                                        alunoTurmas.get(i).getNotaMedia()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaTurma = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CCodigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TabelaTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF Aluno", "Nome Turma", "Codigo Turma", "Nota Media"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaTurmaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaTurma);

        jLabel1.setText("Codigo");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(CCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaTurmaMouseClicked
        int selectedRow = TabelaTurma.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TabelaTurma.getModel();
        AlunoTurma aluno = new AlunoTurma();
        String codigo = model.getValueAt(selectedRow, 2).toString();
        int id = aluno.AlunoTurmaId(this.cpf, codigo);
        TableNotas t = new TableNotas(id, codigo, this.cpf);
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TabelaTurmaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AlunoTurma aluno = new AlunoTurma();
        
        DefaultTableModel Tabela = (DefaultTableModel) TabelaTurma.getModel();
        Tabela.setRowCount(0);
        
        if(CCodigo.getText().isEmpty()){
            ArrayList<AlunoTurma> alunoTurmas = aluno.mostrarAlunoTurma(this.cpf);
            ArrayList<Turma> turmas = new ArrayList();
            Turma turma = new Turma();
            for(int i = 0; i < alunoTurmas.size(); i++){
                Turma atual = turma.mostraTurma(alunoTurmas.get(i).getCodigoTurma());
                turmas.add(atual);
            }
            for(int i = 0; i<alunoTurmas.size(); i++){
                Tabela.addRow(new Object[] {alunoTurmas.get(i).getAlunoCPF(), 
                                            turmas.get(i).getNome(), 
                                            alunoTurmas.get(i).getCodigoTurma(),
                                            alunoTurmas.get(i).getNotaMedia()});
            }
        }else{
            int id = aluno.AlunoTurmaId(this.cpf, CCodigo.getText());
            aluno = aluno.mostrarAlunoTurmaId(id);
            Turma turma = new Turma();
            turma = turma.mostraTurma(CCodigo.getText());
            Tabela.addRow(new Object[] {aluno.getAlunoCPF(), 
                                        turma.getNome(), 
                                        aluno.getCodigoTurma(),
                                        aluno.getNotaMedia()});
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableTurma("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CCodigo;
    public static javax.swing.JTable TabelaTurma;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
